# Generated by Django 3.2.7 on 2024-10-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bulk', '0002_auto_20241009_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/'),
        ),
    ]
