# Generated by Django 3.2.7 on 2024-10-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bulk', '0003_auto_20241009_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_file',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_variant_images/')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Bulk.productvariant')),
            ],
        ),
    ]
