# Generated by Django 3.2.7 on 2024-10-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bulk', '0006_auto_20241010_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
